import { AudioLines, BookOpen, Globe2, Layers3 } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

const AboutSection = () => {
  const { isArabic, tr } = useLanguage();
  const focusAreas = [
    { icon: AudioLines, title: tr('Arabic voice systems', 'أنظمة الصوت العربي'), copy: isArabic ? <>حلول <span className="keep-ltr">TTS</span> و<span className="keep-ltr">ASR</span> واعية باللهجات السعودية والمصرية والعربية الفصحى.</> : 'Dialect-specific TTS and ASR across Saudi, Egyptian, and Modern Standard Arabic.' },
    { icon: Layers3, title: tr('Production ML', 'إنتاج نماذج الذكاء الاصطناعي'), copy: isArabic ? <>تهيئة البيانات وتدريب النماذج وتحسين <span className="keep-ltr">TensorRT</span> والاستدلال الفوري والنشر الموثوق على <span className="keep-ltr">GPU</span>.</> : 'Data curation, model tuning, TensorRT optimization, streaming inference, and reliable GPU deployment.' },
    { icon: Globe2, title: tr('Community building', 'بناء المجتمع التقني'), copy: tr('Manus Fellow and MIE 2026 Chairman, creating hands-on opportunities for Egypt’s AI community.', 'زميل Manus ورئيس مسابقة MIE 2026، أصنع فرصاً عملية لمجتمع الذكاء الاصطناعي في مصر.') },
  ];

  return <section id="about" className="px-6 py-24 md:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.85fr_1.15fr] lg:gap-20"><div><p className="eyebrow">{tr('01 · Overview', '01 · نبذة')}</p><h2 className="section-heading mt-4">{tr('An engineer focused on speech that feels immediate, reliable, and local.', 'مهندس يركز على صوت طبيعي وفوري وموثوق يناسب المستخدم المحلي.')}</h2><div className="mt-7 h-px w-24 bg-cyan-300/50" /></div><div><p className="section-copy text-base md:text-lg">{isArabic ? <>أبني أنظمة <span className="keep-ltr">Voice AI</span> للمتحدثين بالعربية، وأحوّل الأبحاث إلى منتجات يمكن الاعتماد عليها. يجمع عملي بين بيانات الكلام وتكييف النماذج والاستدلال منخفض التأخير وهندسة النشر بدلاً من التعامل معها كمشكلات منفصلة.</> : 'I build Voice AI systems for Arabic-speaking users, translating research into dependable products. My work brings together speech data, model adaptation, low-latency inference, and deployment engineering rather than treating them as separate problems.'}</p><p className="section-copy mt-5 text-base md:text-lg">{isArabic ? <>في <span className="keep-ltr">hams.ai</span> أقود أعمال <span className="keep-ltr">TTS</span> للوكلاء الصوتيين السعوديين الفوريين. منحتني أدواري السابقة في <span className="keep-ltr">GenArabia</span> وAndalusi وE Connect Africa وTensorGraph خبرة تمتد من تدريب النماذج الكبيرة إلى خطوط الكلام وتحسين الأجهزة الطرفية ومنتجات الذكاء الاصطناعي التطبيقية.</> : 'At hams.ai, I lead TTS work for real-time Saudi Arabic voice agents. Earlier roles across GenArabia, Andalusi, E Connect Africa, and TensorGraph gave me experience spanning large-model fine-tuning, speech pipelines, edge optimization, and applied ML products.'}</p><div className="mt-10 grid gap-4 sm:grid-cols-3">{focusAreas.map((area) => { const Icon = area.icon; return <article key={area.title} className="signal-card rounded-2xl p-5"><span className="inline-flex rounded-xl bg-cyan-300/10 p-2.5 text-cyan-200"><Icon className="h-4 w-4" /></span><h3 className="mt-4 font-display text-sm font-bold text-slate-100">{area.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{area.copy}</p></article>; })}</div><div className="mt-8 flex items-center gap-3 rounded-2xl border border-cyan-100/10 bg-cyan-300/[0.035] px-5 py-4"><BookOpen className="h-5 w-5 shrink-0 text-cyan-200" /><p className="text-sm leading-6 text-slate-400">{isArabic ? <>بكالوريوس علوم الحاسب، جامعة حلوان · <span className="keep-ltr">GPA 3.27</span> · بحث منشور لدى <span className="keep-ltr">IEEE</span> في الرؤية الحاسوبية خفيفة الوزن.</> : 'BS in Computer Science, Helwan University · GPA 3.27 · IEEE publication in lightweight computer vision.'}</p></div></div></div></section>;
};

export default AboutSection;
