import { ArrowUpRight } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

const ExperienceTimeline = () => {
  const { isArabic, tr } = useLanguage();
  const roles = [
    { period: 'Feb 2026 — Present', title: tr('AI Engineer · TTS Lead, Voice AI Team', 'مهندس ذكاء اصطناعي · قائد TTS، فريق الذكاء الصوتي'), company: 'hams.ai', highlight: tr('Production Saudi Arabic TTS', 'نظام TTS سعودي جاهز للإنتاج'), summary: tr('Leading the development and operation of Hams Turbo TTS, a production streaming system for live enterprise voice agents.', 'أقود تطوير وتشغيل Hams Turbo TTS، وهو نظام بث جاهز للإنتاج للوكلاء الصوتيين في بيئات الأعمال.'), outcomes: isArabic ? [<>تدريب <span className="keep-ltr">F5-TTS</span> على نحو <span className="keep-ltr">13,600</span> ساعة من الصوت.</>, <>متوسط زمن أول صوت <span className="keep-ltr">154ms</span> مع <span className="keep-ltr">RTF 0.03–0.05</span>.</>, <>تسريع إجمالي يقارب <span className="keep-ltr">9×</span> باستخدام <span className="keep-ltr">TensorRT FP16</span>.</>] : ['Fine-tuned F5-TTS on approximately 13,600 hours of speech.', 'Achieved 154ms mean time-to-first-audio with RTF 0.03–0.05.', 'Delivered ~9× combined speedup through pruned sampling and TensorRT FP16.'] },
    { period: 'Sep 2025 — Jan 2026', title: tr('AI Engineer', 'مهندس ذكاء اصطناعي'), company: 'GenArabia', highlight: tr('Arabic TTS & ATC transcription', 'TTS عربي ونسخ اتصالات الطيران'), summary: tr('Built production speech workflows for Arabic model adaptation, telecom data generation, and air-traffic-control transcription.', 'بنيت خطوط عمل صوتية للإنتاج لتكييف النماذج العربية وتوليد بيانات الاتصالات ونسخ اتصالات المراقبة الجوية.'), outcomes: isArabic ? [<>تدريب <span className="keep-ltr">Spark-TTS</span> للعربية على بيانات منقّاة مدة <span className="keep-ltr">150</span> ساعة.</>, <>خفض معدل خطأ الكلمات في اتصالات الطيران <span className="keep-ltr">60%</span>.</>, <>تصميم خطوط بيانات صوتية اصطناعية ونقاط نشر <span className="keep-ltr">FastAPI</span>.</>] : ['Fine-tuned Spark-TTS for Arabic on a 150-hour curated dataset.', 'Reduced ATC word error rate by 60% with Whisper Large V3 and NVIDIA Parakeet.', 'Designed synthetic speech-data pipelines and deployable FastAPI endpoints.'] },
    { period: 'Jun 2025 — Aug 2025', title: tr('AI Engineer', 'مهندس ذكاء اصطناعي'), company: 'Andalusi', highlight: tr('Edge computer vision', 'رؤية حاسوبية طرفية'), summary: tr('Delivered computer vision capabilities focused on practical deployment and premium product impact.', 'قدمت قدرات للرؤية الحاسوبية مع تركيز على النشر العملي وتأثير المنتج.'), outcomes: tr('Reduced a background-removal model by 75% through quantization.|Shipped an object-removal endpoint for premium users.', 'خفضت حجم نموذج إزالة الخلفية 75% عبر التكميم.|نشرت نقطة إزالة عناصر للمستخدمين المميزين.').split('|') },
    { period: 'Jun 2024 — May 2025', title: tr('AI Engineer', 'مهندس ذكاء اصطناعي'), company: 'E Connect Africa', highlight: tr('Learning experience generation', 'توليد تجارب تعليمية'), summary: tr('Owned speech and audio-visual elements of an AI-powered course-generation product.', 'قدت مكونات الصوت والصورة في منتج لتوليد الدورات مدعوم بالذكاء الاصطناعي.'), outcomes: isArabic ? [<>إدارة <span className="keep-ltr">TTS</span> من إعداد البيانات إلى التسليم.</>, <>بناء خطوط تحريك شخصيات متزامنة باستخدام <span className="keep-ltr">SadTalker</span> و<span className="keep-ltr">Wav2Lip</span> و<span className="keep-ltr">LatentSync</span>.</>] : ['Managed TTS from data preparation to delivery.', 'Built synchronized character-animation pipelines using SadTalker, Wav2Lip, and LatentSync.'] },
  ];

  return <section id="experience" className="px-6 py-24 md:py-32"><div className="mx-auto max-w-6xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><p className="eyebrow">{tr('03 · Experience', '03 · الخبرة')}</p><h2 className="section-heading mt-4">{tr('Work that connects model research to real-world speech products.', 'عمل يربط أبحاث النماذج بمنتجات صوتية واقعية.')}</h2><p className="section-copy mt-5">{tr('I’ve worked across fine-tuning, deployment, and applied product delivery — with a current focus on Arabic voice systems that operate under real-time constraints.', 'عملت في تدريب النماذج والنشر وتسليم المنتجات، مع تركيز حالي على الأنظمة الصوتية العربية التي تعمل ضمن قيود الزمن الحقيقي.')}</p></div><div className="space-y-4">{roles.map((role, index) => <article key={role.company} className="signal-card rounded-2xl p-6 md:p-7"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><p dir="ltr" className="font-mono text-[11px] text-cyan-300">{role.period}</p><h3 className="mt-3 font-display text-lg font-bold tracking-[-0.03em] text-slate-50">{role.title}</h3><p dir="ltr" className="mt-1 text-sm font-medium text-cyan-100">{role.company}</p></div><span className="h-fit rounded-full border border-cyan-100/10 bg-cyan-300/5 px-3 py-1.5 text-[11px] font-medium text-slate-400">{role.highlight}</span></div><p className="mt-5 text-sm leading-6 text-slate-400">{role.summary}</p><ul className="mt-5 space-y-2.5">{role.outcomes.map((outcome, outcomeIndex) => <li key={outcomeIndex} className="flex gap-3 text-sm leading-6 text-slate-300"><ArrowUpRight className={`mt-1 h-3.5 w-3.5 shrink-0 ${index === 0 ? 'text-cyan-200' : 'text-slate-500'} ${isArabic ? 'rotate-90' : ''}`} />{outcome}</li>)}</ul></article>)}</div></div></div></section>;
};

export default ExperienceTimeline;
