import { ArrowUpRight, BookOpenText, FolderGit2, Headphones, MessageSquareMore } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

const PortfolioSection = () => {
  const { isArabic, tr } = useLanguage();
  const projects = [
    { type: tr('Dataset · 2026', 'بيانات · 2026'), title: tr('Large-Scale Saudi Arabic Speech Corpus', 'مجموعة كلام سعودية عربية واسعة النطاق'), description: isArabic ? <>خط متكامل لمجموعة كلام سعودية/خليجية مدته <span className="keep-ltr">1,368</span> ساعة لخدمات <span className="keep-ltr">ASR</span> و<span className="keep-ltr">TTS</span>؛ من انتقاء المصادر والنسخ متعدد المحركات إلى ضبط الجودة والتشكيل وتعليم اللهجة.</> : 'An end-to-end 1,368-hour Saudi/Khaleeji Arabic corpus pipeline for ASR and TTS. The work spans source curation, multi-engine transcription, CER-driven QA, diacritization, and dialect annotation.', metric: '1,368h', metricLabel: tr('curated speech', 'ساعة صوت منقاة'), icon: Headphones, tags: ['Arabic speech', 'ASR', 'TTS', 'Quality control'] },
    { type: tr('Application · 2025', 'تطبيق · 2025'), title: tr('Real-Time Audio Chat with Voice AI', 'محادثة صوتية فورية مع Voice AI'), description: isArabic ? <>تجربة محادثة صوتية تجمع <span className="keep-ltr">VAD</span> و<span className="keep-ltr">Whisper Large v3 Turbo</span> و<span className="keep-ltr">Qwen 3</span> و<span className="keep-ltr">Chatterbox TTS</span> عبر <span className="keep-ltr">WebRTC</span>، مع البث والمقاطعة الطبيعية.</> : 'A conversational voice experience combining VAD, Whisper Large v3 Turbo, Qwen 3 reasoning, and Chatterbox TTS over WebRTC, with streaming and barge-in for natural interruptions.', metric: tr('Live', 'مباشر'), metricLabel: tr('voice interaction', 'تفاعل صوتي'), icon: MessageSquareMore, tags: ['WebRTC', 'Whisper', 'Qwen 3', 'Chatterbox TTS'] },
    { type: tr('Research · 2025', 'بحث · 2025'), title: tr('EgyLens — VQA for Egyptian Arabic', 'EgyLens — أسئلة بصرية باللهجة المصرية'), description: isArabic ? <>تدريب <span className="keep-ltr">Google Gemma 3n</span> للأسئلة البصرية باللهجة المصرية، مع تركيز على الفهم البصري الخاص الذي يعمل على الجهاز ودون اتصال.</> : 'Fine-tuned Google Gemma 3n for Egyptian Arabic visual question answering, with a focus on privacy-preserving, on-device visual understanding and offline inference.', metric: tr('Offline', 'دون اتصال'), metricLabel: tr('private inference', 'استدلال خاص'), icon: FolderGit2, tags: ['Gemma 3n', 'VQA', 'Egyptian Arabic', 'Edge AI'] },
  ];

  return <section id="projects" className="px-6 py-24 md:py-32"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl"><p className="eyebrow">{tr('04 · Selected work', '04 · أعمال مختارة')}</p><h2 className="section-heading mt-4">{tr('A few systems built for Arabic intelligence in the real world.', 'أنظمة مبنية للذكاء العربي في العالم الحقيقي.')}</h2></div><a href="https://github.com/Ahmed-Ezzat20" target="_blank" rel="noopener noreferrer" className="inline-flex w-fit items-center gap-2 text-sm font-semibold text-cyan-100 transition-colors hover:text-cyan-200">{tr('View GitHub', 'استعرض GitHub')}<ArrowUpRight className={`h-4 w-4 ${isArabic ? 'rotate-90' : ''}`} /></a></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{projects.map((project) => { const Icon = project.icon; return <article key={project.title} className="signal-card flex min-h-[350px] flex-col rounded-3xl p-6 md:p-7"><div className="flex items-start justify-between"><span className="rounded-xl bg-cyan-300/10 p-3 text-cyan-200"><Icon className="h-5 w-5" /></span><span className="font-mono text-[10px] uppercase tracking-[0.13em] text-slate-500">{project.type}</span></div><h3 className="mt-8 font-display text-xl font-bold tracking-[-0.035em] text-slate-50">{project.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-auto pt-7"><div className="flex items-end justify-between border-t border-cyan-100/10 pt-5"><div><p dir="ltr" className="metric-value text-2xl">{project.metric}</p><p className="mt-1 text-xs text-slate-500">{project.metricLabel}</p></div><div dir="ltr" className="flex max-w-[180px] flex-wrap justify-end gap-1.5">{project.tags.map((tag) => <span key={tag} className="rounded-full bg-slate-950/30 px-2 py-1 text-[10px] text-slate-400">{tag}</span>)}</div></div></div></article>; })}</div><div className="mt-7 flex items-center gap-3 rounded-2xl border border-cyan-100/10 bg-cyan-300/[0.035] px-5 py-4"><BookOpenText className="h-5 w-5 text-cyan-200" /><p className="text-sm text-slate-400">{isArabic ? <>بحث منشور: <a className="text-cyan-100 underline decoration-cyan-300/30 underline-offset-4 hover:text-cyan-200" href="https://doi.org/10.1109/JAC-ECC64419.2024.11061212" target="_blank" rel="noopener noreferrer"><span className="keep-ltr">Lightweight Plant Leaf Classification Based on Transfer Learning</span></a>، <span className="keep-ltr">IEEE JAC-ECC 2024</span>.</> : <>Published research: <a className="text-cyan-100 underline decoration-cyan-300/30 underline-offset-4 hover:text-cyan-200" href="https://doi.org/10.1109/JAC-ECC64419.2024.11061212" target="_blank" rel="noopener noreferrer">Lightweight Plant Leaf Classification Based on Transfer Learning</a>, IEEE JAC-ECC 2024.</>}</p></div></div></section>;
};

export default PortfolioSection;
